### ISSUE TITLE
The /etc/greenboot/greenboot.conf file is overwritten when upgrading / downgrading the package

### ISSUE THREAD

**Issue by ggiguash** [fedora-iot/greenboot#142] opened 2024-06-18 14:43 UTC
The /etc/greenboot/greenboot.conf file is overwritten when upgrading / downgrading the package. 
This prevents from user customizations to persist following an OS upgrade.

1. `sudo dnf downgrade -y greenboot`
2. Edit or create /etc/greenboot/greenboot.conf 
```
# grep -vE '^$|^#' /etc/greenboot/greenboot.conf 
GREENBOOT_MAX_BOOT_ATTEMPTS=1
GREENBOOT_WATCHDOG_CHECK_ENABLED=true
```
3. `sudo dnf upgrade -y greenboot`
4. Check the file contents
```
# grep -vE '^$|^#' /etc/greenboot/greenboot.conf 
GREENBOOT_WATCHDOG_CHECK_ENABLED=true
```

**Comment by nullr0ute** [comment] 2024-06-18 14:50
Good catch, we need to label that as a config so it doesn't do that. Will have a fix shortly.

**Comment by nullr0ute** [comment] 2024-06-18 15:39
This should be fixed with this update: https://bodhi.fedoraproject.org/updates/FEDORA-2024-db58423740

I've tagged it so it'll appear in the next F-40 compose.

**Comment by ggiguash** [comment] 2024-06-18 16:13
Thank you, @nullr0ute, for the quick fix!

**Comment by miabbott** [comment] 2024-06-18 16:24
I was curious about the commit, so here you go - https://src.fedoraproject.org/rpms/greenboot/c/8e29d4027242c0ffbf1007963ae84b92c278fb74?branch=rawhide

**Comment by nullr0ute** [comment] 2024-06-18 16:27
> I was curious about the commit, so here you go - https://src.fedoraproject.org/rpms/greenboot/c/8e29d4027242c0ffbf1007963ae84b92c278fb74?branch=rawhide

This was the main fix, I did some other cleanup:
       
-            %{_sysconfdir}/%{name}/greenboot.conf
+            %config(noreplace) %{_sysconfdir}/%{name}/greenboot.conf

**Comment by say-paul** [comment] 2024-07-26 07:48
Closing this as the issue is fixed.

**Closed by say-paul** 2024-07-26 07:48 UTC
